- hosts: all
  become: true
  roles:
    - docker

- hosts: jenkins
  become: true
  roles:
  - jenkins
- hosts: manager
  become: true
  roles:
  - manager

- hosts: worker
  become: true
  roles:
  - worker