version: '3.8'
services:
  flaskapp:
    container_name: flaskapp
    build: ./flaskapp
    image: stevenbourn/flaskapp:latest
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
    deploy:
      replicas: 3

  skilltag:
    container_name: skilltag
    build: ./skilltag
    image: stevenbourn/skilltag:latest
    deploy:
      replicas: 3

  specialgen:
    container_name: specialgen
    build: ./specialgen
    image: stevenbourn/specialgen:latest
    deploy:
      replicas: 3
    
  sheetmake:
    container_name: sheetmake
    build: ./sheetmake
    image: stevenbourn/sheetmake:latest
    deploy:
      replicas: 3