---
tasks file for jenkins
- name: install docker-compose
    script: ${workspace}/scripts/docker-compose.sh

- name: install python requisites
  pip:
    requirements: ${workspace}/requirements.txt
    
