---
#tasks file for jenkins
- name: install docker-compose
  script: "{{ playbook_dir }}"/scripts/docker-compose.sh

- name: install python requisites
  pip:
    requirements: "{{ playbook_dir }}"/requirements.txt
    
