---
# tasks file for docker
- name: Install prerequisites
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - python3-pip
    state: latest
    update_cache: true

- name: Add gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  {{ ansible_lsb.codename }} stable"
    state: present

- name: Install Docker Engine
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    update_cache: true

- name: Add ubuntu user to Docker group
  user:
    name: Steven
    groups: docker
    append: true

- name: Pip docker
  pip:
    executable: pip3
    name: docker

- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'
